pds-api #91 : do not support html/xml and force JSON
NASA-PDS/registry-api-service pull request #58
Opened 2021-08-10 19:45 UTC by al-niessner

**Summary***
Removed the XML to HTML/XML converter. Added the request for that format to JSON formatter.

**Test Data and/or Report**
Visited `http://localhost:8080/products` with results attached as image. Converted directly to JSON but you may want HTML/JSON instead.

In chromium, the result of visiting the page results in what looks like an error (because it is an HTML error):

![result](https://user-images.githubusercontent.com/1130658/128924711-a844a95c-b953-4d25-95ca-deb1294f6de8.png)

However, looking at the source of what is returned is actually the JSON:

![source](https://user-images.githubusercontent.com/1130658/128924708-ae104952-f34e-4d3b-b0b9-1745b289d815.png)

Hence, this satisfies the request in that it returns JSON but the real desire may be to have it in HTML/JSON so that it is readable and does not cause the browser to error.

**Related Issues**
None

2021-08-10 19:47 UTC, al-niessner commented
@tloubrieu-jpl @jordanpadams 

Please review this pull request (initial block) for outstanding questions.

2021-08-10 20:39 UTC, al-niessner commented on src/main/java/gov/nasa/pds/api/engineering/configuration/WebMVCConfig.java
> +	public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
fixed

2021-08-26 12:41 UTC, tloubrieu-jpl approved these changes
This pull request is ok for now.

For clearer behavior, I would remove the XML support from the openAPI definition and from the Json serializer.

2021-08-26 12:54 UTC, tloubrieu-jpl requested changes
Sorry, given the error you are showing above on the HTML error, @al-niessner, I will not merge the pull request now.

This error is because you made the Json serializer accept XML or HTML format requests therefore firefox/chrome/... believe this is the format it is getting whereas it is JSON.

To remove this error, you must remove the application/xml support from the swagger definition of the API and remove it from the Json serializer as well. We will also need to remove these lines from the controllers:
```

|| accept.contains("text/html")
|| accept.contains("application/xml")


```


Since I rebase this branch on main, @al-niessner you should pull from origin to get the lqtest version

Thanks

2021-08-31 18:05 UTC, al-niessner commented
Not visible on this pull request are changes taking place in [pds-api-javalib](https://github.com/NASA-PDS/pds-api-javalib/tree/swaggerhub-pds_federated_api-pds-api-91) which is the pushed version from [swagger](https://app.swaggerhub.com/apis/PDS_APIs/pds_federated_api/pds-api-91) that removes all references to application/xml -- but they are only commented out since there is persistence remarks of supporting xml in the future.

2021-08-31 18:21 UTC, al-niessner commented
@jordanpadams @tloubrieu-jpl 

Not happy with error one gets when requesting a format not supported. It is a general error handler that should be specific to application/? is not supported so that the end user clearly knows what to change.

If you agree, then please open a new ticket.

2021-09-01 19:43 UTC, jordanpadams commented
> Not visible on this pull request are changes taking place in [pds-api-javalib](https://github.com/NASA-PDS/pds-api-javalib/tree/swaggerhub-pds_federated_api-pds-api-91) which is the pushed version from [swagger](https://app.swaggerhub.com/apis/PDS_APIs/pds_federated_api/pds-api-91) that removes all references to application/xml -- but they are only commented out since there is persistence remarks of supporting xml in the future.

I just merged these changes into main and pushed to pds-api-javalib: https://github.com/NASA-PDS/pds-api-javalib/commit/8bc11a75ca400943e582a4f25cb425118b4b9452

2021-09-02 14:04 UTC, tloubrieu-jpl approved these changes

2021-09-02 14:05 UTC, tloubrieu-jpl commented
I agree with you @al-niessner the error message should be improved for non accepted format as stated in https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406

I will merge the pull request and create a new ticket to comply with the recommendation on the previous web page.

2021-09-02 14:05 UTC, merged